### PR TITLE
Python Linted + Shell Fixes

### PR DESCRIPTION
**Pull request by harens**
The Python code has been linted with [black](https://github.com/ambv/black)
As well as that, ShellCheck errors [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164) and [SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230) have been corrected

### CODE REVIEW

**Comment by wowkin2** [comment]
What is the reason for changing single quotes to double?
PEP8 does not make a recommendation for this, propose to leave as it was previously.

For some cases, like [here](https://github.com/Kosat/telegram-messages-dump/pull/23/files?utf8=%E2%9C%93&diff=split#diff-602391c523429f065306861871c6a5a6R136), you split 2 lines to 4 lines or [here](https://github.com/Kosat/telegram-messages-dump/pull/23/files?utf8=%E2%9C%93&diff=split#diff-a01040efa682dcf8e6f502c630bb6237R265) to 5. What for? Isn't it better to keep code more compact?

**Comment by harens** [comment]
Thanks for your questions @wowkin2 

Firstly, single quotes were changed to double quotes for the following reasons:

> Why settle on double quotes? They anticipate apostrophes in English text. They match the docstring standard described in PEP 257. An empty string in double quotes ("") is impossible to confuse with a one double-quote regardless of fonts and syntax highlighting used. On top of this, double quotes for strings are consistent with C which Python interacts a lot with.

You can find this in [black's documentation](https://github.com/ambv/black#strings)

However, if @Kosat or yourself still prefer single quotes, let me know and I would be more than happy to change it

Finally, in the examples you have given, extra indentation was added to conform to the [PEP8 Style Guide on Indentation](https://www.python.org/dev/peps/pep-0008/#indentation)

I hope this helped!

**Comment by wowkin2** [comment]
Why do you prefer black instead of flake8 or pylint or something else? They doesn't have any concerns about quotes.
I think the vote from @Kosat can decide which style we'll use.

The first example, by [link you provided](https://www.python.org/dev/peps/pep-0008/#indentation) shows the style that @Kosat used for most cases (`Aligned with opening delimiter`). Don't see any reason to change it to the second sample (`More indentation included to distinguish this from the rest.`)

**Comment by harens** [comment]
Thanks again for your questions @wowkin2 

**Flake8**

There is no _Flake8 or Black_, for you can use both together. Even Black itself has a [.flake8](https://github.com/ambv/black/blob/master/.flake8). As Black's [documentation](https://black.readthedocs.io/en/stable/the_black_code_style.html) notes:

>If you’re using Flake8, you can bump `max-line-length to 88` and forget about it. Alternatively, use [Bugbear](https://github.com/PyCQA/flake8-bugbear)’s B950 warning instead of E501 and keep the max line length at 80 which you are probably already using.

**Pylint**

As with Flake8, there is no _Pylint or black_ situation. As this [pylint issue](https://github.com/PyCQA/pylint/issues/2154) shows, black can be integrated with pylint

 **Quotes**

For the quotes, you can configure black to not change them with `--skip-string-normalization`. However, for the reasons I have already stated, I chose not to do this. Again though, I would be more than happy to undo this if you or @Kosat wish.

**Why Black?**

Overall, this brings about the question, why not use Flake8 or Pylint individually? 
Not only can Black be used together with these linters, but it is however the self-described _Uncompromising Code Formatter_

It is extremely fast, and doesn't badger you with formatting.

I have nothing to gain from praising Black, and I am in no way associated with them whatsoever. Of course it's not perfect, however, I have always found it a very useful linter.

Even Kenneth Reitz, the creator of [requests](https://github.com/requests/requests), said that:
>This [black] vastly improves the formatting of our code. Thanks a ton!

**Indentation**
As for the final point, a similar question was raised and answered in one of [black's issues](https://github.com/ambv/black/issues/48#issuecomment-401007037)

Thanks again for the questions, and I hope this answered them!

**Comment by reorx** [comment]
Black's taste on double quote is actually not widely accepted by the community, if you search "double quote" in Black's issues you can find a lot of people oppose against it.

And since Black is "uncompromising", I don't see any chance that it may support single quote formatting in the future. I'd suggest using `--skip-string-normalization` so that there won't be so much differences in code. Trying to introduce rules to a project is painful sometimes, so at least let the result be friendly to the author.

**Comment by Kosat** [comment]
Hi @harens,

At this point I don't see enough reasons to adopt Black or any other linters/plugins to stricken the rules on the code here. Thus there's no much sense to accept your formatting changes per se.

Thanks for your efforts but unfortunately for now I'll have to decline your PR.

**Pull request closed without merging**
